### ISSUE TITLE
Scripts snes et nes exécuté lors du lancement d'un jeux super snes

### ISSUE THREAD

**Issue by lernico** [b0b33140/RetroBat-WS2812B#1]
Les mauvais jeux sont lancés, il faut voir l'argument donné aux scripts d’exécution pour appliquer le filtre correct.

Une piste:

`
@echo off
set system=snes\\

Rem recuperer ce qui est passé en parametre
echo %* > toto.txt

Rem si le chemin est complet
If exist d:/%system%/%* echo le fichier existe 1
Rem si le chemin est complet (que le nom de la rom
If exist %* echo le fichier existe 1
`

**Comment by b0b33140** [comment]
La commande `If exist` ne  filtre pas les systèmes, elle exécute tout le temps la commande suivante.
Mais j'ai trouvé une autre solution avec `findstr` en ajoutant le chemin dossier précédent : 
`set system=roms\nes\\`
`set system=roms\snes\\`
